version: '3.8'

services:
  bug-reproduction-engine:
    volumes:
      # Mount source code for development
      - ./templates:/app/templates
      - ./static:/app/static
      - ./app.py:/app/app.py
      # Persist data
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
      - "3001:3001"
      - "80:80"
