
name: Deploy BTS

on:
  push:
    branches: [ "main" ]
    paths:
      - 'bts/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: |
          bts/package-lock.json
          bts/src/backend/package-lock.json
    
    # Build frontend
    - name: Install frontend dependencies
      working-directory: ./bts
      run: npm ci
    
    - name: Run frontend tests
      working-directory: ./bts
      run: npm run test:ci
    
    - name: Build frontend production
      working-directory: ./bts
      run: npm run build
      env:
        REACT_APP_API_URL: ${{ secrets.PRODUCTION_API_URL || 'http://localhost:3001/api' }}
        CI: false # Treats warnings as warnings, not errors
    
    # Prepare backend
    - name: Install backend dependencies
      working-directory: ./bts/src/backend
      run: npm ci --only=production
    
    - name: Run backend tests
      working-directory: ./bts/src/backend
      run: npm test
      # Deploy to hosting service (example using GitHub Pages for frontend)
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./bts/build
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
    
    # For backend, you'd typically deploy to a service like:
    # - Heroku
    # - AWS EC2/Lambda
    # - DigitalOcean
    # - Vercel
    # - Railway
    # Example for backend deployment notification
    - name: Backend Deployment Note
      run: |
        echo "Backend needs to be deployed to a Node.js hosting service"
        echo "Popular options: Heroku, Railway, Render, DigitalOcean App Platform"
        echo "Backend files are ready in ./bts/src/backend/"
