name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "bts/**"
      - ".github/workflows/node.js.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "bts/**"
      - ".github/workflows/node.js.yml"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: "npm"
        cache-dependency-path: |
          bts/package-lock.json
          bts/src/backend/package-lock.json
    
    - name: Install frontend dependencies
      working-directory: ./bts
      run: |
        rm -f package-lock.json
        npm install
    
    - name: Build frontend
      working-directory: ./bts
      run: npm run build --if-present
      env:
        CI: false
    
    - name: Test frontend
      working-directory: ./bts
      run: npm run test:ci --if-present
      
    - name: Install backend dependencies
      working-directory: ./bts/src/backend
      run: npm ci
    
    - name: Test backend
      working-directory: ./bts/src/backend
      run: npm test --if-present
